// client-vue/src/views/Login.vue
<template>
  <form @submit.prevent="handleSubmit">
    <h2>Entrar</h2>
    <input
      type="email"
      placeholder="Email"
      id="email"
      v-model="email"
      required
    />
    <input
      type="password"
      placeholder="Senha"
      id="password"
      v-model="password"
      required
    />
    <button type="submit">Entrar</button>
    <p v-if="error" style="color: red;">{{ error }}</p>
    <p v-if="success" style="color: green;">Login realizado com sucesso!</p>
  </form>
</template>

<script>
import { useStore } from 'vuex';
import { useRouter } from 'vue-router';
import '../styles/login.scss';

export default {
  name: 'Login',
  data() {
    return {
      email: '',
      password: '',
      error: '',
      success: false,
    };
  },
  methods: {
    async handleSubmit() {
      console.log('Dados do formulário:', { email: this.email, password: this.password });

      try {
        // Dispatch para login via Vuex
        await this.$store.dispatch('login', { email: this.email, password: this.password });

        // Verifica se o token foi recuperado após a ação do Vuex
        const token = this.$store.state.token;  
        if (token) {
          localStorage.setItem('token', token);
          this.success = true;
          this.error = '';

          window.location.reload(); 
        } else {
          console.error('Erro: Token não encontrado.');
          this.error = 'Erro ao autenticar, tente novamente.';
        }
      } catch (err) {
        this.error = 'Falha no login. Tente novamente.';
        this.success = false;
        console.error('Erro:', err);
      }
    },
  },
};
</script>

// client-nextjs/src/pages/login.tsx
import React, { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { loginUser } from '../store/actions/userActions';

import { useRouter } from 'next/router';
import { setUserToken, setUserError } from '../store/slices/userSlice';  
import styles from '../styles/login.module.scss';
import { AppDispatch } from '@/store';

const LoginPage: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);

  const dispatch = useDispatch<AppDispatch>();
  const router = useRouter();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const token = localStorage.getItem('token');
      if (!token) {
        router.push('/'); 
      }
    }
  }, [router]);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    try {
      const result = await dispatch(loginUser(email, password));  

      if (result && result.token) {
        dispatch(setUserToken(result.token));
        setError(null);
        router.push('/dashboard');
      } else {
        dispatch(setUserError('Erro ao fazer login. Tente novamente.'));
      }
    } catch (error) {
      dispatch(setUserError('Erro inesperado ao fazer login.'));
      console.error('Erro inesperado ao fazer login:', error);
    }
  };

  return (
    <main className={styles.mainContainer}>
      <form onSubmit={handleSubmit} className={styles.loginForm}>
        <h2 className={styles.title}>Entrar</h2>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
          className={styles.inputField}
        />
        <input
          type="password"
          placeholder="Senha"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
          className={styles.inputField}
        />
        <button type="submit" className={styles.submitButton}>Entrar</button>
        {error && <p className={styles.error}>{error}</p>}
      </form>
    </main>
  );
};

export default LoginPage;
