// client-vue/src/views/Register.vue
<template>
    <form @submit.prevent="handleSubmit">
      <h2>Cadastrar</h2>
      <input
        type="text"
        placeholder="Nome"
        id="name"
        v-model="name"
        required
        autocomplete="name"
      />
      <input
        type="email"
        placeholder="Email"
        id="email"
        v-model="email"
        required
        autocomplete="email"
      />
      <input
        type="password"
        placeholder="Senha"
        id="password"
        v-model="password"
        required
        autocomplete="new-password"
      />
      <button type="submit">Cadastrar</button>
      <p v-if="error" style="color: red;">{{ error }}</p>
      <p v-if="success" style="color: green;">Cadastro realizado com sucesso!</p>
    </form>
  </template>
  
  <script>
  import { useRouter } from 'vue-router';
  import { useStore } from 'vuex';
  import { register } from '../store/actions';
  import '../styles/register.scss';
  
  export default {
  name: 'Register',
  data() {
    return {
      name: '',
      email: '',
      password: '',
      error: '',
      success: false,
    };
  },
  computed: {
    errorFromStore() {
      return this.$store.state.error;
    },
    successFromStore() {
      return this.$store.state.success;
    },
  },
  methods: {
    async handleSubmit() {
      console.log('Dados do formulário de registro:', { name: this.name, email: this.email, password: this.password });

      try {
        // Dispatch para registrar
        await this.$store.dispatch('register', { name: this.name, email: this.email, password: this.password });

        // Verifica se o registro foi bem-sucedido
        console.log('Verificando sucesso no Vuex:', this.successFromStore);

        if (this.successFromStore) {
          this.success = true;
          this.error = '';

          window.location.reload(); 

        } else {
          console.error('Erro: Registro não foi bem-sucedido.');
          this.error = this.errorFromStore || 'Erro ao registrar, tente novamente.';
        }
      } catch (err) {
        console.error('Erro ao realizar o registro:', err);
        this.error = 'Falha no cadastro. Tente novamente.';
        this.success = false;
      }
    },
  },
};
</script>

// client-nextjs/src/pages/register.tsx
import React, { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { registerUser } from '../store/actions/userActions';
import { useRouter } from 'next/router';
import { AppDispatch } from '@/store';
import styles from '../styles/register.module.scss';

const RegisterPage: React.FC = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);

  const dispatch = useDispatch<AppDispatch>();
  const router = useRouter();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const token = localStorage.getItem('token');
      if (!token) {
        router.push('/'); 
      }
    }
  }, [router]);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();

    try {
      const result = await dispatch(registerUser(name, email, password));
      if (result) {
        setError(null);
        router.push('/dashboard'); 
      } else {
        setError('Erro ao registrar. Tente novamente.');
      }
    } catch (error) {
      setError('Falha no registro. Tente novamente.');
      console.error('Erro ao registrar:', error);
    }
  };

  return (
    <form onSubmit={handleSubmit} className={styles.registerForm}>
      <h2 className={styles.title}>Registrar</h2>
      <input
        type="text"
        placeholder="Nome"
        value={name}
        onChange={(e) => setName(e.target.value)}
        required
        className={styles.inputField}
      />
      <input
        type="email"
        placeholder="Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        required
        className={styles.inputField}
      />
      <input
        type="password"
        placeholder="Senha"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        required
        className={styles.inputField}
      />
      <button type="submit" className={styles.submitButton}>
        Registrar
      </button>
      {error && <p className={styles.errorMessage}>{error}</p>}
    </form>
  );
};

export default RegisterPage;
