// client-react/src/components/Dashboard.tsx
import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import '../styles/dashboard.scss';

const Dashboard: React.FC = () => {
    const navigate = useNavigate();

    useEffect(() => {
        const token = localStorage.getItem('token');
        
        if (!token) {
            navigate('/login');
        }
    }, [navigate]);

    const logout = () => {
        localStorage.removeItem('token');
        setTimeout(() => {
            navigate('/'); 
            window.location.reload(); 
        }, 1000); 
    };

    return (
        <div className="dashboard-container">
            <h2>Bem-vindo ao Dashboard</h2>
            <p>Esta é a área logada. Somente usuários autenticados podem ver esta página.</p>
            <button className="logout-button" onClick={logout}>Sair</button>
        </div>
    );
};

export default Dashboard;

// client-angular-18/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  constructor(private router: Router) {}

  ngOnInit(): void {
    const token = localStorage.getItem('token');
    
    if (!token) {
      this.router.navigate(['/login']);
    }
  }

  logout(): void {
    localStorage.removeItem('token');
    setTimeout(() => {
      this.router.navigate(['/']);
      window.location.reload();
    }, 1000);
  }
}

<div class="dashboard-container">
    <h2>Bem-vindo ao Dashboard</h2>
    <p>Esta é a área logada. Somente usuários autenticados podem ver esta página.</p>
    <button class="logout-button" (click)="logout()">Sair</button>
  </div>
