// client-angular-18/src/app/containers/app-container.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HeaderComponent } from '../components/header/header.component';
import { FooterComponent } from '../components/footer/footer.component';
import { DashboardComponent } from '../components/dashboard/dashboard.component';
import { LoginComponent } from '../components/login/login.component';
import { RegisterComponent } from '../components/register/register.component';
import { CommonModule } from '@angular/common'; 

@Component({
  selector: 'app-container',
  standalone: true,
  imports: [
    CommonModule,  
    HeaderComponent,
    FooterComponent,
    DashboardComponent,
    LoginComponent,
    RegisterComponent
  ],
  templateUrl: './app-container.component.html',
  styleUrls: ['./app-container.component.scss']
})
export class AppContainerComponent implements OnInit {
  token: string | null = localStorage.getItem('token');
  activeTab: 'login' | 'register' = 'login';

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.setActiveTabFromRoute();

    // Observa mudanças de rota para atualizar a aba ativa
    this.router.events.subscribe(() => {
      this.setActiveTabFromRoute();
    });
  }

  private setActiveTabFromRoute(): void {
    const path = this.router.url;
    if (path === '/login') {
      this.activeTab = 'login';
    } else if (path === '/register') {
      this.activeTab = 'register';
    }
  }

  handleLogout(): void {
    localStorage.removeItem('token');
    this.token = null;
    this.router.navigate(['/']);
  }

  showTab(tabName: 'login' | 'register'): void {
    this.activeTab = tabName;
    this.router.navigate([`/${tabName}`]);
  }
}

<app-header></app-header>

<div *ngIf="token; else authTabs">
  <app-dashboard></app-dashboard>
  <button (click)="handleLogout()">Sair</button>
</div>

<ng-template #authTabs>
  <div class="tabs">
    <button (click)="showTab('login')">Entrar</button>
    <button (click)="showTab('register')">Cadastrar</button>
  </div>
  <div id="content" [ngSwitch]="activeTab">
    <app-login *ngSwitchCase="'login'"></app-login>
    <app-register *ngSwitchCase="'register'"></app-register>
  </div>
</ng-template>

<app-footer></app-footer>

// client-react/src/containers/AppContainer.tsx
import React, { useEffect, useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Login from '../components/Login';
import Register from '../components/Register';
import Dashboard from '../components/Dashboard';
import '../styles/tabs.scss';

const AppContainer: React.FC = () => {
    const [token, setToken] = useState<string | null>(localStorage.getItem('token'));
    const [activeTab, setActiveTab] = useState<'login' | 'register'>('login');

    useEffect(() => {
        const handleRouteChange = () => {
            const path = window.location.pathname;
            if (path === '/login') {
                setActiveTab('login');
            } else if (path === '/register') {
                setActiveTab('register');
            }
        };

        window.onpopstate = handleRouteChange;
        handleRouteChange();

        return () => {
            window.onpopstate = null;
        };
    }, []);

    const handleLogout = () => {
        localStorage.removeItem('token');
        setToken(null);
        window.location.href = '/';
    };

    const showTab = (tabName: 'login' | 'register') => {
        setActiveTab(tabName);
        window.history.pushState({}, '', `/${tabName}`);
    };

    return (
        <div>
            <Header />
            {token ? (
                <>
                    <Dashboard />
                    <button onClick={handleLogout}>Sair</button>
                </>
            ) : (
                <>
                    <div className="tabs">
                        <button onClick={() => showTab('login')}>Entrar</button>
                        <button onClick={() => showTab('register')}>Cadastrar</button>
                    </div>
                    <div id="content">
                        {activeTab === 'login' ? <Login /> : <Register />}
                    </div>
                </>
            )}
            <Footer />
        </div>
    );
};

export default AppContainer;
