// client-react/src/components/Dashboard.tsx
import React, { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import '../styles/dashboard.scss';

const Dashboard: React.FC = () => {
    const navigate = useNavigate();

    useEffect(() => {
        const token = localStorage.getItem('token');
        
        if (!token) {
            navigate('/login');
        }
    }, [navigate]);

    const logout = () => {
        localStorage.removeItem('token');
        setTimeout(() => {
            navigate('/'); 
            window.location.reload(); 
        }, 1000); 
    };

    return (
        <div className="dashboard-container">
            <h2>Bem-vindo ao Dashboard</h2>
            <p>Esta é a área logada. Somente usuários autenticados podem ver esta página.</p>
            <button className="logout-button" onClick={logout}>Sair</button>
        </div>
    );
};

export default Dashboard;

// client-vue/src/views/Dashboard.vue
<template>
    <div class="dashboard-container">
      <h2>Bem-vindo ao Dashboard</h2>
      <p>Esta é a área logada. Somente usuários autenticados podem ver esta página.</p>
      <button class="logout-button" @click="logout">Sair</button>
    </div>
  </template>
  
  <script>
  import { onMounted } from 'vue';
  import { useRouter } from 'vue-router';
  import '../styles/dashboard.scss';
  
  export default {
    name: 'Dashboard',
    setup() {
      const router = useRouter();
  
      onMounted(() => {
        const token = localStorage.getItem('token');
        if (!token) {
          router.push('/login');
        }
      });
  
      const logout = () => {
        localStorage.removeItem('token');
        setTimeout(() => {
          router.push('/');
          window.location.reload();
        }, 1000);
      };
  
      return {
        logout
      };
    }
  };
  </script>
