// client-react/src/components/Register.tsx
import React, { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { register } from '../redux/actions/userActions';
import { AppDispatch, RootState } from '../redux/store';
import '../styles/register.scss';

const Register: React.FC = () => {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const [success, setSuccess] = useState(false);

    const dispatch = useDispatch<AppDispatch>();
    const token = useSelector((state: RootState) => state.user.token);

    const handleSubmit = async (event: React.FormEvent) => {
        event.preventDefault();

        //console.log('Dados do formulário:', { name, email, password });

        try {
            // Dispatch do registro via Redux
            await dispatch(register(name, email, password));

            setSuccess(true);
            setError('');
            
            setTimeout(() => {
                window.location.href = '/Dashboard';
            }, 1000);

        } catch (error) {
            setError('Falha no registro. Tente novamente.');
            setSuccess(false);
            console.error('Erro:', error);
        }
    };


    useEffect(() => {
        // Verifica se o token foi salvo após o registro
        if (success && token) {
            localStorage.setItem('token', token);
            setTimeout(() => {
                window.location.reload();  
            }, 1000);
        }
    }, [success, token]);
    

    return (
        <form onSubmit={handleSubmit}>
            <h2>Cadastrar</h2>
            <input
                type="text"
                placeholder="Nome"
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
            />
            <input
                type="email"
                placeholder="Email"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
            />
            <input
                type="password"
                placeholder="Senha"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
            />
            <button type="submit">Cadastrar</button>
            {error && <p style={{ color: 'red' }}>{error}</p>}
            {success && <p style={{ color: 'green' }}>Cadastro realizado com sucesso!.</p>}
        </form>
    );
};

export default Register;

// client-vue/src/views/Register.vue
<template>
    <form @submit.prevent="handleSubmit">
      <h2>Cadastrar</h2>
      <input
        type="text"
        placeholder="Nome"
        id="name"
        v-model="name"
        required
        autocomplete="name"
      />
      <input
        type="email"
        placeholder="Email"
        id="email"
        v-model="email"
        required
        autocomplete="email"
      />
      <input
        type="password"
        placeholder="Senha"
        id="password"
        v-model="password"
        required
        autocomplete="new-password"
      />
      <button type="submit">Cadastrar</button>
      <p v-if="error" style="color: red;">{{ error }}</p>
      <p v-if="success" style="color: green;">Cadastro realizado com sucesso!</p>
    </form>
  </template>
  
  <script>
  import { useRouter } from 'vue-router';
  import { useStore } from 'vuex';
  import { register } from '../store/actions';
  import '../styles/register.scss';
  
  export default {
  name: 'Register',
  data() {
    return {
      name: '',
      email: '',
      password: '',
      error: '',
      success: false,
    };
  },
  computed: {
    errorFromStore() {
      return this.$store.state.error;
    },
    successFromStore() {
      return this.$store.state.success;
    },
  },
  methods: {
    async handleSubmit() {
      console.log('Dados do formulário de registro:', { name: this.name, email: this.email, password: this.password });

      try {
        // Dispatch para registrar
        await this.$store.dispatch('register', { name: this.name, email: this.email, password: this.password });

        // Verifica se o registro foi bem-sucedido
        console.log('Verificando sucesso no Vuex:', this.successFromStore);

        if (this.successFromStore) {
          this.success = true;
          this.error = '';

          window.location.reload(); 

        } else {
          console.error('Erro: Registro não foi bem-sucedido.');
          this.error = this.errorFromStore || 'Erro ao registrar, tente novamente.';
        }
      } catch (err) {
        console.error('Erro ao realizar o registro:', err);
        this.error = 'Falha no cadastro. Tente novamente.';
        this.success = false;
      }
    },
  },
};
</script>
